openapi: "3.0.3"

info:
  title: "Sample-API"
  version: "1.0.0"

paths:
  "/hello":
    get:
      responses:
        "200":
          description: "200 OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  massage: 
                    type: string
                    example: "Hello World"
